outcome_always_hide <- c(
  "row_id",
  "char_row_id",
  "Covidence ID",
  "Study Label with subgroup indication",
  "Type of Outcome", # raw name that later becomes Type of Estimate
  # "Domain",                               # add this if you also want to hide the domain column
  "Minimum Age (days)",
  "Maximum Age (days)",
  "Minimum Age",
  "Maximum Age",
  "Point Estimate",
  "Estimate Type",
  "CI Lower",
  "CI Upper",
  "Study Design Specifics",
  # "Definition [of outcome]",
  "Notes 1",
  "Notes 2",
  "Risk of Bias domains marked Some Concerns (RoB2) or Moderate (ROBINS-I)",
  "Risk of Bias domains marked High (RoB2) or Serious/Critical (ROBINS-I)",
  "Intervention",
  "Comparator",
  "Strain Targeted by Intervention Vaccine",
  # "Factors Adjusted",
  "Strain Targeted by Comparator Vaccine",
  "Study Period Start",
  "Study Period End",
  "Vaccine",
  "Link",
  "Follow-up (days)"
)

outcome_column_order <- c(
  "row_id",
  "char_row_id",
  "Study Label",
  "Study Label with subgroup indication",
  "Covidence ID",
  "Type of Estimate",
  "Study Design",
  "Population",
  "Age Range",
  "Minimum Age",
  "Maximum Age",
  "Study Period",
  "Study Period Start",
  "Study Period End",
  # "Vaccine",
  "Comparison", # renamed
  "Outcome",
  "Definition [of outcome]",
  "Follow-up",
  "Follow-up (days)",
  "Intervention",
  "Vaccine Formulation for Intervention Arm",
  "Strain Targeted by Intervention Vaccine",
  "Number of events in intervention arm",
  "Sample size intervention",
  "Comparator",
  "Vaccine Formulation for Comparator Arm",
  "Strain Targeted by Comparator Vaccine",
  "Number of events in comparator arm",
  "Sample size comparator",
  "Number of events (ecological studies)",
  "N total (ecological studies)",
  "Estimate (95% CI)",
  "Estimate Type",
  "Definition [of outcome]",
  "Factors Adjusted",
  "Risk of Bias"
)

outcome_desired_widths <- c(
  "Study Label" = 100,
  "Type of Estimate" = 100,
  "Study Design" = 120,
  "Population" = 120,
  "Age Range" = 100,
  # "Vaccine" = 120,
  "Comparison" = 120, # ← renamed
  "Outcome" = 100,
  "Factors Adjusted" = 170,
  "Estimate (95% CI)" = 120,
  "Risk of Bias" = 100
)
